# Generated by Django 5.0.7 on 2024-07-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='objects/images/')),
                ('release_date', models.DateField()),
                ('video_url', models.URLField(blank=True)),
            ],
        ),
    ]
